services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
    volumes:
      - ./backend:/app
      - /app/venv/
    environment:
      - DATABASE_URL=sqlite:///./ct_scan_centers.db
    env_file:
      - ./backend/.env
    stdin_open: true
    tty: true
 
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3030:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_BACKEND_URL=https://sales.biocliq.ai/compass
    stdin_open: true
    tty: true
    depends_on:
      - backend